const assert=require('node:assert/strict');
const path=require('node:path');
const runtime=process.env.ORIENT_PLAYWRIGHT||(process.env.ORIENT_PLAYWRIGHT||'playwright');
const {chromium}=require(runtime);
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.ORIENT_URL||'http://127.0.0.1:4173'));
 await page.getByRole('button',{name:'Add a place',exact:true}).click();
 await page.locator('[name=name]').fill('My comic shop');
 await page.getByRole('button',{name:'Add to My Map',exact:true}).click();
 assert.match(await page.locator('#lookup-status').innerText(),/Find an address/);
 assert.ok(await page.locator('#add-dialog').isVisible());
 let calls=0;
 await page.route('**/api/geocode',async route=>{calls++;assert.equal(route.request().method(),'POST');await route.fulfill({json:{results:[{name:'Comic shop match',address:'123 Main St, Toledo, Ohio',coordinates:[-83.60,41.70]},{name:'Another shop',address:'456 Main St, Toledo, Ohio',coordinates:[-83.61,41.71]}]}});});
 await page.locator('[name=address]').fill('123 Main St Toledo Ohio');
 assert.equal(calls,0,'Typing must not trigger an external lookup');
 await page.getByRole('button',{name:'Find address',exact:true}).click();
 await page.locator('[data-location="0"]').waitFor();
 assert.equal(await page.locator('.lookup-result').count(),2);
 await page.screenshot({path:path.join(__dirname,'output/playwright/address-matches.png')});
 await page.locator('[data-location="0"]').click();
 await page.getByRole('button',{name:'Add to My Map',exact:true}).click();
 assert.equal(await page.locator('#sheet h2').innerText(),'My comic shop');
 await page.evaluate(()=>document.querySelector('#sheet button.expand[aria-expanded=false]')?.click()); await page.getByRole('button',{name:/^Log a visit to/}).click();
 let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1')));
 const id=data.custom[0].id;assert.deepEqual(data.custom[0].coordinates,[-83.60,41.70]);
 await page.getByRole('button',{name:'Edit place or address',exact:false}).click();
 await page.locator('[name=address]').fill('456 Main St Toledo Ohio');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 assert.ok(await page.locator('#add-dialog').isVisible(),'Changed address requires a new match');
 await page.getByRole('button',{name:'Find address',exact:true}).click();
 await page.locator('[data-location="1"]').click();
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 data=await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1')));
 assert.equal(data.custom.length,1);assert.equal(data.custom[0].id,id);assert.deepEqual(data.custom[0].coordinates,[-83.61,41.71]);assert.ok(data.visited.includes(id));assert.ok(data.saved.includes(id));
 await page.reload();
 await page.getByRole('button',{name:'My Map',exact:true}).click();
 await page.evaluate(()=>document.querySelector('#sheet button.expand').click());
 await page.getByRole('button',{name:'Edit place or address',exact:false}).click();
 await page.unroute('**/api/geocode');
 await page.route('**/api/geocode',r=>r.fulfill({json:{results:[]}}));
 await page.locator('[name=address]').fill('No match');
 await page.getByRole('button',{name:'Find address',exact:true}).click();
 await page.getByText('No matches found.',{exact:false}).waitFor();
 await page.unroute('**/api/geocode');
 await page.route('**/api/geocode',r=>r.fulfill({status:502,json:{error:'Lookup unavailable. Try the map center.'}}));
 await page.getByRole('button',{name:'Find address',exact:true}).click();
 await page.getByText('Lookup unavailable.',{exact:false}).waitFor();
 assert.equal(await page.locator('[data-action=lookup]').isDisabled(),false);
 assert.deepEqual(errors,[]);
 console.log('PASS: explicit lookup, match selection, no silent map-center save, edit/re-geocode preserves marks and ID, reload, empty and failure states.');
 // One live request verifies the proxy and upstream response, independent of UI fixtures.
 const live=await page.request.post((process.env.ORIENT_URL||'http://127.0.0.1:4173')+'/api/geocode',{data:{query:'1 Government Center, Toledo, OH 43604'}});
 const payload=await live.json();assert.equal(live.status(),200,JSON.stringify(payload));if(!payload.results.length){console.log('SKIP: live Census lookup returned no match');return;}console.log('PASS: live address lookup returned '+payload.results.length+' matches. First: '+payload.results[0].address);
 if(payload.results.length)assert.match(payload.results[0].address,/1 GOVERNMENT CTR/);if(payload.results.length)assert.match(payload.results[0].accuracy,/Estimated/);
 await page.unroute('**/api/geocode');
 await page.locator('[name=address]').fill('1 Government Center, Toledo, OH 43604');
 await page.getByRole('button',{name:'Find address',exact:true}).click();
 await page.locator('[data-location="0"]').waitFor();
 assert.equal(await page.locator('.lookup-result').count(),1);
 assert.match(await page.locator('.lookup-result').innerText(),/Estimated position/);
 await page.screenshot({path:path.join(__dirname,'output/playwright/address-match.png')});
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
