const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium}=require((process.env.ORIENT_PLAYWRIGHT||'playwright'));
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.locator('#sheet .expand').first().click();
 await page.getByRole('button',{name:'Edit hours, people & notes'}).click();
 await page.locator('#knowledge-dialog [name=hours]').fill('Wednesday 10–7');
 await page.locator('#knowledge-dialog [name=people]').fill('Sam — owner <script>');
 await page.locator('#knowledge-dialog [name=note]').fill('Ask about new releases.');
 await page.getByRole('button',{name:'Save place details'}).click();
 assert.match(await page.locator('#sheet').innerText(),/Sam — owner <script>/);
 await page.locator('.place-quick input').fill('Wednesday is new comic day');
 await page.locator('.place-quick button').click();
 assert.equal(await page.locator('#event-dialog [name=repeat]').inputValue(),'weekly');
 assert.equal(await page.locator('#event-dialog [name=time]').inputValue(),'');
 assert.equal(await page.locator('#event-dialog [name=placeId]').inputValue(),'toledo-pantry-26');
 await page.getByRole('button',{name:'Save calendar entry'}).click();
 await page.getByRole('button',{name:'Calendar',exact:true}).click();
 assert.match(await page.locator('#panel').innerText(),/Wednesday is new comic day/);
 const before=await page.locator('.calendar-entry').count();assert.ok(before>5);
 await page.locator('[data-cal=skip]').first().click();assert.equal(await page.locator('.calendar-entry').count(),before-1);
 await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();
 assert.equal(await page.locator('.calendar-entry').count(),before-1);
 await page.locator('[data-cal=edit]').first().click();
 await page.locator('#event-dialog [name=title]').fill('New comic Wednesday');
 await page.getByRole('button',{name:'Save calendar entry'}).click();
 assert.match(await page.locator('#panel').innerText(),/New comic Wednesday/);
 await page.getByRole('button',{name:'Month',exact:true}).click();
 await page.locator('.calendar-grid [data-cal=day]').first().click();
 await page.screenshot({path:path.join(__dirname,'output/playwright/calendar-month.png')});
 for(const width of [320,390,1200]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 const results=await page.evaluate(()=>{
  const C=OrientCalendar,weekly=C.parse('Every Tuesday, 2 for 1 al pastor tacos'),timed=C.parse('Trivia every Thursday 7pm to 9pm');
  const e={...weekly,id:'a',placeId:'p',date:'2026-10-06',until:'2026-10-27'};
  const dates=C.occurrences([e],'2026-10-01','2026-10-31').map(o=>o.date);
  const monthly=C.occurrences([{...e,date:'2026-01-31',repeat:'monthly',until:'2026-03-31'}],'2026-01-01','2026-03-31').map(o=>o.date);
  const raw=JSON.parse(localStorage.getItem('orient-field-map-v1')),ids=new Set(['toledo-pantry-26']);
  return {weekly,timed,dates,monthly,clean:C.clean(raw,ids)};
 });
 assert.deepEqual(results.weekly.days,['TU']);assert.equal(results.weekly.kind,'Special');
 assert.equal(results.timed.time,'19:00');assert.equal(results.timed.end,'21:00');
 assert.deepEqual(results.dates,['2026-10-06','2026-10-13','2026-10-20','2026-10-27']);
 assert.deepEqual(results.monthly,['2026-01-31','2026-03-31']);
 assert.equal(results.clean.events.length,1);assert.match(results.clean.details['toledo-pantry-26'].people,/Sam/);
 await page.getByRole('button',{name:'Open settings',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export my map',exact:true}).click();
 const download=await downloadPromise,exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(exported.events[0].title,'New comic Wednesday');assert.equal(exported.events[0].skip.length,1);
 page.once('dialog',d=>d.accept());
 await page.locator('#import-file').setInputFiles({name:'map.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
 await page.getByRole('button',{name:'Calendar',exact:true}).click();
 await page.getByRole('button',{name:'Agenda',exact:true}).click();
 assert.equal(await page.locator('.calendar-entry').count(),before-1);
 await page.screenshot({path:path.join(__dirname,'output/playwright/calendar-agenda.png')});
 page.once('dialog',d=>d.accept());await page.locator('[data-cal=delete]').first().click();
 assert.equal(await page.locator('[data-cal=delete]').count(),0);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1')).events.length),0);
 assert.ok(await page.getByRole('link',{name:'Published specials source'}).count()>0,'Deleting personal events preserves shared specials');
 assert.deepEqual(errors,[]);await browser.close();console.log('Calendar checks passed: recurrence, skip, persistence, private details, drafts, responsive layouts.');
})().catch(e=>{console.error(e);process.exit(1)});
