'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),D=require('./public/commons-data.js');
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const repoName=value=>{const match=String(value||'').trim().replace(/^https:\/\/github\.com\//,'').replace(/\/$/,'').match(/^([A-Za-z0-9-]+)\/([A-Za-z0-9_.-]+)$/);if(!match||['.','..'].includes(match[2]))throw fail('Choose a GitHub repository as owner/repository.');return match[1]+'/'+match[2].replace(/\.git$/,'');};
async function github(token,route,{method='GET',body,fetcher=fetch,missing=false}={}){const r=await fetcher('https://api.github.com'+route,{method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'Orient-place-commons'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000),redirect:'error'});if(missing&&r.status===404)return null;if(!r.ok)throw fail(r.status===401?'GitHub authorization expired. Reconnect GitHub.':r.status===403?'GitHub refused this action. Check repository permissions or rate limits.':r.status===422?'GitHub could not create this contribution yet. A new fork may still be preparing; retry shortly.':'GitHub request failed ('+r.status+'). Retry without changing the reviewed contribution.',r.status===401?401:502);return r.status===204?null:r.json();}
async function publish(raw,{token,login,fetcher=fetch}={}){
  if(!raw||Object.keys(raw).some(k=>!['repository','bundle'].includes(k)))throw fail('Send only a repository and the reviewed public bundle.');
  const repository=repoName(raw.repository);let bundle;try{bundle=D.validate(raw.bundle);}catch(e){throw fail(e.message);}if(!bundle.claims.length)throw fail('Choose at least one observation.');
  const call=(route,options={})=>github(token,route,{...options,fetcher}),base=await call('/repos/'+repository);if(base.private||base.archived||base.disabled)throw fail('Choose an active public commons repository.');if(!base.default_branch)throw fail('Initialize this repository with a README first.');
  const hash=crypto.createHash('sha256').update(JSON.stringify(bundle)).digest('hex').slice(0,24),branch='orient/contribution-'+hash,filename='contributions/'+hash+'.json';let writable=repository;
  if(!base.permissions?.push){let fork=await call('/repos/'+login+'/'+base.name,{missing:true});if(fork&&(!fork.fork||fork.parent?.full_name?.toLowerCase()!==repository.toLowerCase()))throw fail('A repository with this name already exists in your account and is not a fork of the selected commons.');if(!fork)fork=await call('/repos/'+repository+'/forks',{method:'POST',body:{default_branch_only:true}});writable=fork.full_name;if(!writable||!writable.toLowerCase().startsWith(login.toLowerCase()+'/'))throw fail('GitHub did not return your contribution fork.',502);}
  const owner=writable.split('/')[0],head=owner+':'+branch,existing=await call('/repos/'+repository+'/pulls?state=all&head='+encodeURIComponent(head));if(existing.length){const pr=existing[0];return {url:pr.html_url,number:pr.number,state:pr.state,merged:!!pr.merged_at,existing:true,repository};}
  const baseRef=await call('/repos/'+repository+'/git/ref/heads/'+encodeURIComponent(base.default_branch),{missing:true});if(!baseRef)throw fail('Initialize this commons repository with a README before publishing.');let ref=await call('/repos/'+writable+'/git/ref/heads/'+branch,{missing:true});if(!ref){ref=await call('/repos/'+writable+'/git/refs',{method:'POST',body:{ref:'refs/heads/'+branch,sha:baseRef.object.sha}});}
  const file=await call('/repos/'+writable+'/contents/'+filename+'?ref='+encodeURIComponent(branch),{missing:true});if(file){let actual;try{actual=JSON.parse(Buffer.from(file.content||'','base64').toString());}catch{}if(!D.same(actual,bundle))throw fail('The contribution branch changed outside Orient. Review it on GitHub before retrying.',409);}if(!file)await call('/repos/'+writable+'/contents/'+filename,{method:'PUT',body:{message:'Contribute '+bundle.claims.length+' place observation'+(bundle.claims.length===1?'':'s'),branch,content:Buffer.from(JSON.stringify(bundle,null,2)+'\n').toString('base64')}});
  const diff=await call('/repos/'+writable+'/compare/'+baseRef.object.sha+'...'+encodeURIComponent(branch));if(!Array.isArray(diff.files)||diff.files.length!==1||diff.files[0].filename!==filename||diff.files[0].status!=='added')throw fail('The branch contains changes outside your reviewed bundle. No pull request was opened.',409);
  const pr=await call('/repos/'+repository+'/pulls',{method:'POST',body:{title:'Orient: '+bundle.claims.length+' reviewed place observation'+(bundle.claims.length===1?'':'s'),head,base:base.default_branch,body:'Explicitly reviewed and submitted from Orient.\n\nPublic bundle: `'+filename+'`\n\nContains coordinate-anchored places and sourced claims under CC BY 4.0. No private map fields or neighbor entries are included. Please review the observations and provenance before accepting.\n\nIf this repository uses the Orient commons template, the Check contribution workflow validates this file and merging adds it to snapshot.json. Otherwise import the bundle through Field kit → Place commons.'}});return {url:pr.html_url,number:pr.number,state:pr.state,existing:false,repository};
}
function vault(dir=process.env.ORIENT_DATA_DIR||path.join(__dirname,'data')){const file=path.join(dir,'github-connections.json'),keyFile=path.join(dir,'github-connections.key');function key(){fs.mkdirSync(dir,{recursive:true});try{return fs.readFileSync(keyFile);}catch{const k=crypto.randomBytes(32);fs.writeFileSync(keyFile,k,{mode:0o600,flag:'wx'});return k;}}function read(){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return {};}}function write(values){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(values),{mode:0o600});fs.renameSync(file+'.tmp',file);}return {get(id){if(!/^[a-f0-9]{64}$/.test(id||''))return null;const item=read()[id];if(!item||item.expires<Date.now())return null;try{const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(item.iv,'hex'));decipher.setAuthTag(Buffer.from(item.tag,'hex'));return {login:item.login,token:Buffer.concat([decipher.update(Buffer.from(item.value,'hex')),decipher.final()]).toString()};}catch{return null;}},set(token,login){const values=read(),id=crypto.randomBytes(32).toString('hex'),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv),value=Buffer.concat([cipher.update(token),cipher.final()]);for(const k of Object.keys(values))if(values[k].expires<Date.now())delete values[k];values[id]={login,expires:Date.now()+90*86400000,iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex'),value:value.toString('hex')};write(values);return id;},remove(id){const values=read();delete values[id];write(values);}};}
function createHandler({fetcher=fetch,storage=vault()}={}){const busy=new Set();return async function handle(req,res,url,json,sync){if(!sync.authorized(req)){json(res,401,{error:'Pair this browser in Field kit before connecting or publishing to GitHub.'});return;}const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host)throw Error();}catch{json(res,403,{error:'Use Orient on this site to publish.'});return;}}
  const id=(req.headers.cookie||'').match(/(?:^|;\s*)orient_github=([a-f0-9]{64})(?:;|$)/)?.[1],session=storage.get(id),secure=req.headers['x-forwarded-proto']==='https'||!!req.socket.encrypted;
  const cookie=(value,age)=>res.setHeader('Set-Cookie','orient_github='+value+'; HttpOnly; SameSite=Strict; Path=/api/commons; Max-Age='+age+(secure?'; Secure':''));
  if(url==='/api/commons/github'&&req.method==='GET'){json(res,200,{connected:!!session,login:session?.login||''});return;}
  if(req.method!=='POST'){json(res,405,{error:'Use POST.'});return;}if(!(req.headers['content-type']||'').startsWith('application/json')){json(res,415,{error:'Use JSON.'});return;}
  let lock;try{let text='';for await(const c of req){text+=c;if(Buffer.byteLength(text)>1024*1024)throw fail('Contribution exceeds 1 MB.',413);}const raw=JSON.parse(text);
    if(url==='/api/commons/github/disconnect'){if(id)storage.remove(id);cookie('',0);json(res,200,{connected:false});return;}
    if(url==='/api/commons/github/connect'){if(typeof raw.token!=='string'||raw.token.length<20||raw.token.length>300||Object.keys(raw).some(k=>k!=='token'))throw fail('Enter a GitHub access token.');const user=await github(raw.token,'/user',{fetcher});if(!/^[A-Za-z0-9-]+$/.test(user.login||''))throw fail('GitHub did not return a valid account.',502);const next=storage.set(raw.token,user.login);if(id)storage.remove(id);cookie(next,90*86400);json(res,200,{connected:true,login:user.login});return;}
    if(url!=='/api/commons/publish')throw fail('Unknown commons endpoint.',404);if(!session)throw fail('Connect GitHub once before publishing.',401);if(busy.has(id))throw fail('A contribution is already being submitted. Please wait.',429);busy.add(id);lock=id;const result=await publish(raw,{...session,fetcher});json(res,200,result);
  }catch(e){json(res,e.status||502,{error:e instanceof SyntaxError?'Invalid contribution JSON.':e.message||'GitHub publishing failed. Your private map is unchanged.'});}finally{if(lock)busy.delete(lock);}
};}
module.exports={publish,github,repoName,vault,createHandler};
