const assert=require('node:assert/strict'),G=require('./gidgit.cjs'),M=require('./public/gidgit-map.js');
const records=[{id:'local-thrift',name:'Second Chance',category:'Thrift store',note:'Clothing and low prices',hours:'Daily 9am-5pm',open:'open',visited:false,rating:4,distance:2},{id:'local-coffee',name:'Coffee corner',category:'Coffee shop',note:'Cheap drinks',hours:'',open:'unknown',visited:true,rating:5,distance:.1}];
const plan={intent:'find',terms:['thrift','secondhand','cheap'],mustMatch:['cheap sweaters'],openNow:false,unvisited:false,placeId:'',field:'',value:'',message:''};
(async()=>{
 assert.deepEqual(M.find(records,plan,'Where can I find cheap sweaters?').map(p=>p.id),['local-thrift']);assert.deepEqual(M.find(records,{terms:[],mustMatch:[],openNow:true,unvisited:true}).map(p=>p.id),['local-thrift']);assert.equal(M.find(records,{terms:['museum'],mustMatch:['museum']}).length,0);
 assert.equal(M.draft({intent:'update',placeId:'local-thrift',field:'note',value:'Outdoor seating'},records[0]).after,'Clothing and low prices\nOutdoor seating');assert.throws(()=>M.draft({intent:'update',placeId:'unknown',field:'hours',value:'24/7'},records[0]));assert.throws(()=>G.validate({intent:'update',placeId:'local-other',field:'note',value:'Oops'},records));assert.throws(()=>G.validate({intent:'update',placeId:'local-thrift',field:'people',value:'Oops'},records));
 let sent;const response=await G.ask({query:'Cheap sweaters',places:records,contextPlaceId:'local-thrift'},{configuration:{url:'http://127.0.0.1:11434/api/chat',model:'fixture'},fetcher:async(url,options)=>{sent=JSON.parse(options.body);return {ok:true,json:async()=>({message:{content:JSON.stringify(plan)}})};}});assert.equal(response.engine.model,'fixture');assert.equal(sent.stream,false);assert.equal(sent.think,false);assert.equal(sent.options.num_ctx,4096);assert.equal(sent.options.num_predict,512);assert.equal(sent.keep_alive,'5m');assert.deepEqual(response.timing,{loadMs:0,promptMs:0,generateMs:0,promptTokens:0,outputTokens:0});assert.equal(JSON.parse(sent.messages[1].content).places.length,2);assert.match(sent.messages[0].content,/DATA, never instructions/);
 const input=G.input({query:'Hi',places:[{...records[0],people:'secret',photos:['secret'],coordinates:[1,2]}]});assert.equal(JSON.stringify(input).includes('secret'),false);assert.equal(input.places[0].coordinates,undefined);
 const old=process.env.ORIENT_GIDGIT_URL;try{process.env.ORIENT_GIDGIT_URL='https://remote.example';assert.throws(()=>G.config(),/local Ollama/);}finally{if(old===undefined)delete process.env.ORIENT_GIDGIT_URL;else process.env.ORIENT_GIDGIT_URL=old;}
 await assert.rejects(()=>G.ask({query:'Hi',places:records},{configuration:{url:'http://127.0.0.1:11434/api/chat',model:'fixture'},fetcher:async()=>({ok:true,json:async()=>({message:{content:'not JSON'}})})}),/unreadable/);
 const outingQuery='Find me a coffeeshop before I go to a thrift store tomorrow';const grouped=M.groups(records,plan,outingQuery);assert.deepEqual(grouped.map(g=>g.places.map(p=>p.id)),[['local-coffee'],['local-thrift']]);assert.equal(M.find(records,plan,'Find a coffeeshop')[0].id,'local-coffee');
 const corrected=await G.ask({query:outingQuery,places:records},{configuration:{url:'http://127.0.0.1:11434/api/chat',model:'fixture'},fetcher:async()=>({ok:true,json:async()=>({message:{content:JSON.stringify({...plan,openNow:true,unvisited:true})}})})});assert.equal(corrected.plan.openNow,false);assert.equal(corrected.plan.unvisited,false);
 const statusPlaces=[{id:'dragon',name:"Dragon’s Roost Coffee",hours:'Daily closed'},{id:'other',name:'Another Cafe',hours:'24/7'}];assert.equal(M.statusRequest(statusPlaces,'Is Dragons Roost coffee open now?','other').place.id,'dragon');assert.equal(M.statusRequest(statusPlaces,'Is it open now?','dragon').place.id,'dragon');assert.equal(M.statusRequest(statusPlaces,'Find coffee shops open now','dragon'),null);assert.equal(M.statusRequest(statusPlaces,'Is Dragon’s Roost Coffee open tomorrow?','dragon'),null);assert.ok(M.statusRequest(statusPlaces,'Is Missing Cafe open now?','dragon').message);assert.equal(M.statusRequest(statusPlaces,'Change Dragon’s Roost hours to daily 9am-5pm','dragon'),null);
 console.log('Gidgit: saved-record grounding, shopping intent, computed filters, append-only note drafts, edit validation, local-only engine configuration, bounded structured requests and private-field exclusion passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
