const assert=require('node:assert/strict'),path=require('node:path'),{geocode}=require('./geocode.cjs');
const {chromium}=require(process.env.ORIENT_PLAYWRIGHT||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{
  let url;const fetcher=async u=>{url=new URL(u);return {ok:true,json:async()=>({features:[{geometry:{type:'Point',coordinates:[-83.743,42.28]},properties:{name:'Ann Arbor',state:'Michigan',country:'United States',osm_key:'place',osm_value:'city'}}]})};};
  const cities=await geocode('Ann Arbor, Michigan',fetcher,{city:true});assert.equal(cities.results[0].name,'Ann Arbor');assert.deepEqual(url.searchParams.getAll('layer'),['city']);assert.equal(url.searchParams.has('lat'),false);
  await geocode('Comic shop',fetcher,{center:[-83.743,42.28]});assert.equal(url.searchParams.get('lon'),'-83.743');assert.equal(url.searchParams.get('lat'),'42.28');
  await geocode('Comic shop',fetcher);assert.equal(url.searchParams.has('lat'),false);
  const browser=await chromium.launch({channel:'chrome',headless:true});try{
    const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],catalogRequests=[],geocodes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/catalog\.(local|sample)\.js/.test(r.url()))catalogRequests.push(r.url());});
    await page.route('**/api/state**',r=>r.fulfill({status:403,contentType:'application/json',body:'{"error":"Isolated test"}'}));
    await page.route('https://tiles.openfreemap.org/styles/liberty',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({version:8,sources:{},layers:[]})}));
    await page.route('**/api/geocode',r=>{const body=r.request().postDataJSON();geocodes.push(body);const isDetroit=body.query.includes('Detroit');r.fulfill({contentType:'application/json',body:JSON.stringify({results:[{name:isDetroit?'Detroit':'Ann Arbor',address:isDetroit?'Detroit, Michigan, United States':'Ann Arbor, Michigan, United States',coordinates:isDetroit?[-83.0458,42.3314]:[-83.743,42.28]}]})});});
    await page.route('**/api/places',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({places:[{id:'osm-node-12345',name:'Michigan fixture coffee',kind:'Coffee shop',icon:'coffee',coordinates:[-83.743,42.28]}]})}));
    await page.goto(process.env.ORIENT_URL||'http://127.0.0.1:4176');await page.locator('#home-dialog').waitFor({state:'visible'});assert.deepEqual(catalogRequests,[]);assert.equal(await page.locator('.area').innerText(),'Choose city');
    await page.locator('[name=city]').fill('Ann Arbor, Michigan');assert.equal(geocodes.length,0);await page.getByRole('button',{name:'Find my city',exact:true}).click();await page.locator('[data-home-match]').click();assert.equal(geocodes[0].city,true);assert.equal(geocodes[0].center,undefined);
    await page.screenshot({path:'output/playwright/home-setup-mobile.png'});await page.locator('[data-home-save]').click();assert.equal(await page.locator('.area').innerText(),'Ann Arbor');assert.equal(await page.locator('#home-dialog').isVisible(),false);assert.deepEqual(catalogRequests,[]);
    let store=await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1')));assert.equal(store.home.name,'Ann Arbor');assert.equal(store.useCatalog,false);assert.deepEqual(store.saved,[]);
    await page.locator('[data-action="discover-home"]').click();await page.getByText('Michigan fixture coffee',{exact:true}).first().waitFor();await page.locator('.row[data-place="osm-node-12345"]').click();await page.locator('.grip').press('End');await page.locator('[data-action="save"]').click();
    await page.getByRole('button',{name:'Explore',exact:true}).click();assert.match(await page.locator('#panel').innerText(),/Around Ann Arbor/);await page.locator('[data-outing-open]').click();assert.match(await page.locator('#outing-origin').innerText(),/Ann Arbor/);await page.locator('[data-outing-close]').click();
    // Home area can be changed while preserving the user's saved map.
    await page.locator('[data-action="settings"]').click();await page.locator('[data-home-open]').click();await page.locator('[name=city]').fill('Detroit, Michigan');await page.getByRole('button',{name:'Find my city',exact:true}).click();await page.locator('[data-home-match]').click();await page.locator('[data-home-confirm] summary').click();await page.locator('[name=home-zone]').selectOption('America/Chicago');await page.locator('[data-home-save]').click();
    store=await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1')));assert.equal(store.home.name,'Detroit');assert.equal(store.home.timeZone,'America/Chicago');assert.ok(store.saved.includes('osm-node-12345'));
    await page.reload();await page.waitForFunction(()=>window.OrientHome?.home()?.name==='Detroit');assert.equal(await page.locator('#home-dialog').count(),0);assert.deepEqual(catalogRequests,[]);await page.getByRole('button',{name:'Calendar',exact:true}).click();assert.match(await page.locator('#panel').innerText(),/America\/Chicago/);
    await page.getByRole('button',{name:'Explore',exact:true}).click();await page.locator('[data-action="add"]:visible').first().click();await page.locator('[data-action="add-name"]').click();await page.locator('#add-form [name=address]').fill('Comic shop, Detroit');await page.locator('[data-action="lookup"]').click();await page.locator('[data-location]').first().waitFor();assert.deepEqual(geocodes.at(-1).center,[-83.0458,42.3314]);await page.locator('[data-action="close-add"]').click();
    // An existing browser keeps its map and Toledo default without being forced through setup.
    await page.evaluate(()=>localStorage.setItem('orient-field-map-v1',JSON.stringify({version:1,custom:[{id:'local-legacy',name:'Legacy fixture',kind:'Other',coordinates:[-83.539,41.655]}],saved:['local-legacy'],visited:[]})));await page.reload();await page.waitForFunction(()=>window.OrientHome?.home()?.name==='Toledo');assert.equal(await page.locator('#home-dialog').count(),0);assert.ok(catalogRequests.length>0);assert.equal(await page.evaluate(()=>OrientHome.home().name),'Toledo');
    assert.deepEqual(errors,[]);console.log('Home area: unbiased city search, fresh-map catalog isolation, Michigan discovery, Today/outings origin, persistent changes/time zone, place-search bias and legacy migration passed.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
