const H=require('./check-helpers.cjs');
// Optional browser check. Uses the bundled Playwright runtime; no application dependencies.
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const runtime = process.env.ORIENT_PLAYWRIGHT || (process.env.ORIENT_PLAYWRIGHT||'playwright');
const { chromium } = require(runtime);
(async()=>{
  const out=path.join(__dirname,'output/playwright');fs.mkdirSync(out,{recursive:true});
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await H.seed(page,{useCatalog:true});
  await page.goto((process.env.ORIENT_URL||'http://127.0.0.1:4173'));
  await H.openDefault(page);await H.map(page);await page.locator('.map-marker').first().waitFor();
  await page.waitForTimeout(4500);
  await page.screenshot({path:path.join(out,'mobile-explore.png')});
  await page.evaluate(()=>document.querySelector('#sheet button.expand[aria-expanded=false]')?.click());
  await page.locator('#sheet .save').click();
  await page.evaluate(()=>document.querySelector('#sheet button.expand[aria-expanded=false]')?.click()); await page.getByRole('button',{name:/^Log a visit to/}).click();
  await page.getByRole('button',{name:'My Map',exact:true}).click();
  assert.match(await page.locator('#context').innerText(),/1 SAVED · 1 VISITED/);
  await page.reload();
  await page.getByRole('button',{name:'My Map',exact:true}).click();
  assert.match(await page.locator('#context').innerText(),/1 SAVED · 1 VISITED/);
  await H.add(page);await H.pick(page);
  await page.locator('[name=name]').fill('My test place <script>');
  await page.locator('[name=note]').fill('A place to try.');
  await page.locator('#coordinate-details summary').click();
  await page.getByRole('button',{name:'Use current map center',exact:true}).click();
  await page.getByRole('button',{name:'Add to My Map',exact:true}).click();
  assert.equal(await page.locator('#sheet h2').innerText(),'My test place <script>');
  assert.equal(await page.getByRole('link',{name:'Directions',exact:true}).count(),1);
  await page.screenshot({path:path.join(out,'mobile-personal-place.png')});
  await page.getByRole('button',{name:'Explore',exact:true}).click();
  await page.locator('#search').fill('NO SUCH PLACE');
  assert.match(await page.locator('#panel').innerText(),/Nothing found/);
  await page.locator('#search').fill('');
  const known=await page.evaluate(()=>String(window.ORIENT_CATALOG[0].name));
  await page.locator('#search').fill(known);
  assert.match(await page.locator('#panel').innerText(),new RegExp(known.replace(/[.*+?^${}()|[]\]/g,'\$&')));
  await page.locator('#search').fill('');
  await page.getByRole('button',{name:'Explore',exact:true}).click();
  await H.list(page);
  await page.getByRole('button',{name:'Open settings',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export my map',exact:true}).click();
  const download=await downloadPromise;
  const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.custom.length,1);
  await page.getByRole('button',{name:'Close',exact:true}).last().click();
  for(const size of [{width:320,height:568},{width:390,height:844},{width:1280,height:800}]){
    await page.setViewportSize(size);
    await page.getByRole('button',{name:'Explore',exact:true}).click();
    await page.waitForTimeout(200);
    const metrics=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,nav:document.querySelector('.bottom-nav').getBoundingClientRect().bottom,height:innerHeight}));
    assert.ok(metrics.scroll<=metrics.width,JSON.stringify(metrics));assert.ok(metrics.nav<=metrics.height+1,JSON.stringify(metrics));
    await page.screenshot({path:path.join(out,`layout-${size.width}.png`)});
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: save/visit/reload, custom place, search/empty state, export, 320/390/1280 layouts; no runtime errors.');
  assert.ok(await page.locator('#map-status').isHidden(),'Map should finish loading');
  console.log('PASS: live Toledo basemap loaded.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
