if(!require('node:fs').existsSync(require('node:path').join(__dirname,'public/catalog.local.js'))){console.log('SKIP: needs public/catalog.local.js (a local catalog of places)');process.exit(0);}
const assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require((process.env.ORIENT_PLAYWRIGHT||'playwright'));
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.ORIENT_URL||'http://127.0.0.1:4173'));await page.locator('#sheet').waitFor();
const entries=await page.evaluate(()=>OrientWebsite.allEvents().filter(e=>e.sharedSource));assert.equal(entries.length,35);assert.equal(new Set(entries.map(e=>e.placeId)).size,20);
assert.equal(entries.filter(e=>e.placeId==='food-special-2').length,4);assert.equal(entries.find(e=>e.placeId==='food-special-2').time,'17:00');assert.equal(entries.find(e=>e.placeId==='food-special-8').days[0],'TU');assert.equal(entries.find(e=>e.placeId==='food-special-8').time,'');
const occurrences=await page.evaluate(()=>OrientCalendar.occurrences(OrientWebsite.allEvents().filter(e=>e.placeId==='food-special-8'),'2026-10-08','2026-10-21'));assert.deepEqual(occurrences.map(e=>e.date),['2026-10-13','2026-10-20']);
await page.locator('[data-tab="Calendar"]').click();await page.locator('#search').fill('Home Slice');assert.ok(await page.locator('.calendar-entry').count()>0);assert.match(await page.locator('#panel').innerText(),/personal pizza/);assert.equal(await page.locator('[data-cal="delete"]').count(),0);assert.ok(await page.getByRole('link',{name:'Published specials source'}).count()>0);
await page.locator('[data-cal="month"]').click();assert.ok(await page.locator('.calendar-grid b').count()>0);
await page.locator('[data-tab="Explore"]').click();await page.locator('#search').fill('margaritas');assert.match(await page.locator('#panel').innerText(),/Bier Stube/);
await page.locator('#search').fill('');await page.getByRole('button',{name:'Filter places',exact:true}).click();await page.locator('[data-filter="Specials"]').click();await page.getByRole('button',{name:'Switch to list',exact:true}).click();assert.equal(await page.locator('#panel [data-place]').count(),20);await page.locator('#panel [data-place="food-special-2"]').click();await page.evaluate(()=>document.querySelector('#sheet button.expand[aria-expanded=false]')?.click());assert.match(await page.locator('#sheet').innerText(),/4 recurring specials/);await page.evaluate(()=>document.querySelectorAll('#sheet details.fold').forEach(d=>{d.open=true;}));assert.match(await page.locator('#sheet').innerText(),/personal pizza/);assert.doesNotMatch(await page.locator('#sheet').innerText(),/See weekly specials in note/);
await page.setViewportSize({width:320,height:844});await page.locator('[data-tab="Calendar"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'output/playwright/shared-specials.png'});
await page.reload();assert.equal(await page.evaluate(()=>OrientWebsite.allEvents().filter(e=>e.sharedSource).length),35);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('orient-field-map-v1'))?.events?.length||0),0);assert.deepEqual(errors,[]);console.log('PASS: 20 venues / 35 shared specials, weekday recurrence, map filter, offer search, agenda/month, sources, no private duplication, reload and 320px.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});

