const Social=require('./public/social.js');
// Bounded public-site reader. No browser execution, search engine, or model.
const http=require('node:http'),https=require('node:https'),dns=require('node:dns').promises,net=require('node:net'),crypto=require('node:crypto');
const ical=require('./ical.cjs');
const TZ='America/New_York',MAX_BYTES=2*1024*1024;
const special6=new net.BlockList();special6.addSubnet('2001::',23,'ipv6');special6.addSubnet('2001:db8::',32,'ipv6');special6.addSubnet('2002::',16,'ipv6');special6.addSubnet('3fff::',20,'ipv6');
const clip=(s,n=800)=>String(s??'').replace(/\s+/g,' ').trim().slice(0,n);
function decode(s){return String(s??'').replace(/&(#x[\da-f]+|#\d+|amp|quot|apos|lt|gt|nbsp);/gi,(_,v)=>{if(v[0]==='#'){const n=parseInt(v.slice(v[1].toLowerCase()==='x'?2:1),v[1].toLowerCase()==='x'?16:10);return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';}return {amp:'&',quot:'"',apos:"'",lt:'<',gt:'>',nbsp:' '}[v.toLowerCase()];});}
const plain=s=>clip(decode(String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')));
const hash=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,20);
function publicIP(ip){if(net.isIP(ip)===4){const a=ip.split('.').map(Number);return !([0,10,127].includes(a[0])||a[0]>=224||a[0]===169&&a[1]===254||a[0]===172&&a[1]>=16&&a[1]<=31||a[0]===192&&(a[1]===168||a[1]===0||a[1]===2)||a[0]===100&&a[1]>=64&&a[1]<=127||a[0]===198&&(a[1]===18||a[1]===19||a[1]===51)||a[0]===203&&a[1]===0&&a[2]===113);}return net.isIP(ip)===6&&/^[23][0-9a-f]{3}:/i.test(ip)&&!special6.check(ip,'ipv6');}
function normalize(input){let s=clip(input,2048).replace(/^webcals?:\/\//i,'https://');if(!/^[a-z][a-z\d+.-]*:/i.test(s))s='https://'+s;let u;try{u=new URL(s);}catch{throw new Error('Enter a valid public website address.');}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port&&!['80','443'].includes(u.port)||!u.hostname.includes('.')&&!net.isIP(u.hostname.replace(/[\[\]]/g,'')))throw new Error('Use a public HTTP or HTTPS website without credentials.');u.hash='';return u.href;}
async function fetchPublic(input,redirects=0){const url=normalize(input),u=new URL(url),host=u.hostname.replace(/[\[\]]/g,'');let lookupTimer;let addresses;try{addresses=await Promise.race([dns.lookup(host,{all:true}),new Promise((_,reject)=>{lookupTimer=setTimeout(()=>reject(new Error('Website name lookup timed out.')),5000);})]);}finally{clearTimeout(lookupTimer);}if(!addresses.length||addresses.some(a=>!publicIP(a.address)))throw new Error('Only public websites can be read. Local and private network addresses are blocked.');const pinned=addresses[0];return new Promise((resolve,reject)=>{const req=(u.protocol==='https:'?https:http).get(u,{headers:{'User-Agent':'Orient/0.5 (public place and calendar reader)','Accept':'text/html, text/calendar, application/ld+json, application/json;q=0.8'},lookup:(_h,o,cb)=>o.all?cb(null,[pinned]):cb(null,pinned.address,pinned.family)},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();if(redirects>=3||!res.headers.location){reject(new Error('Too many website redirects.'));return;}let next;try{next=new URL(res.headers.location,url);if(u.protocol==='https:'&&next.protocol!=='https:')throw new Error();}catch{reject(new Error('Unsafe website redirect.'));return;}fetchPublic(next.href,redirects+1).then(resolve,reject);return;}if(res.statusCode<200||res.statusCode>=300){res.resume();reject(Object.assign(new Error('Website returned HTTP '+res.statusCode+'. It may block automated readers.'),{httpStatus:res.statusCode}));return;}const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>MAX_BYTES){req.destroy(new Error('Website response is too large to read.'));return;}chunks.push(chunk);});res.on('end',()=>resolve({url,body:Buffer.concat(chunks).toString('utf8'),type:String(res.headers['content-type']||'')}));res.on('error',reject);});const deadline=setTimeout(()=>req.destroy(new Error('Website took too long to respond.')),10000);req.once('close',()=>clearTimeout(deadline));req.setTimeout(10000,()=>req.destroy(new Error('Website took too long to respond.')));req.on('error',reject);});}
function robotsAllows(body,path){const groups=[];let agents=[],rules=[];function flush(){if(agents.length)groups.push({agents,rules});agents=[];rules=[];}for(const line of String(body).split(/\r?\n/)){const m=line.replace(/#.*/,'').match(/^\s*(user-agent|allow|disallow)\s*:\s*(.*?)\s*$/i);if(!m)continue;if(m[1].toLowerCase()==='user-agent'){if(rules.length)flush();agents.push(m[2].toLowerCase());}else if(m[2])rules.push({allow:m[1].toLowerCase()==='allow',path:m[2]});}flush();const specific=groups.filter(g=>g.agents.some(a=>a.includes('orient'))),use=specific.length?specific:groups.filter(g=>g.agents.includes('*'));let best=null;for(const g of use)for(const r of g.rules){const pattern='^'+r.path.replace(/[.+?^{}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*');let match=false;try{match=new RegExp(pattern).test(path);}catch{}if(match&&(!best||r.path.length>best.path.length||r.path.length===best.path.length&&r.allow))best=r;}return !best||best.allow;}
function attributes(tag){const a={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))a[m[1].toLowerCase()]=decode(m[2]??m[3]??m[4]);return a;}
function links(html,url){const out=[];for(const m of html.matchAll(/<(a|link)\b([^>]*?)(?:>([\s\S]*?)<\/a>|>)/gi)){const a=attributes(m[2]);if(!a.href)continue;try{const href=new URL(a.href.replace(/^webcals?:\/\//i,'https://'),url);if(['http:','https:'].includes(href.protocol))out.push({url:href.href,label:plain(m[3]||a.title||''),type:a.type||'',calendar:/^webcals?:/i.test(a.href)});}catch{}}return out;}
function nodes(html){const out=[];let count=0;function walk(v,depth=0){if(!v||typeof v!=='object'||depth>18||count++>10000)return;if(Array.isArray(v)){v.forEach(x=>walk(x,depth+1));return;}if(v['@type'])out.push(v);for(const val of Object.values(v))if(val&&typeof val==='object')walk(val,depth+1);}for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(attributes(m[1]).type?.toLowerCase()!=='application/ld+json')continue;try{walk(JSON.parse(m[2]));}catch{}}return out;}
function wall(value){const s=String(value||'');if(!/^\d{4}-\d{2}-\d{2}(?:$|T)/.test(s))return null;const date=s.slice(0,10);if(ical.fromNum(ical.toNum(date))!==date)return null;if(s.length===10)return {date,time:'',dateOnly:true};if(/(?:Z|[+-]\d{2}:?\d{2})$/i.test(s)){const n=Date.parse(s);return Number.isFinite(n)?{...ical.wallOf(n,TZ),dateOnly:false}:null;}const time=s.slice(11,16);return /^([01]\d|2[0-3]):[0-5]\d$/.test(time)?{date,time,dateOnly:false}:null;}
function structuredEvents(ns,url){const out=[];for(const n of ns){const types=[].concat(n['@type']||[]);if(!types.some(t=>/Event$/.test(t))||/cancel/i.test(String(n.eventStatus)))continue;const s=wall(n.startDate),e=wall(n.endDate);if(!s||!n.name)continue;out.push({uid:clip(n['@id']||n.url||hash(n.name+s.date+s.time),300),title:clip(n.name,140),detail:plain(n.description),location:clip(n.location?.name||''),url,allDay:s.dateOnly,start:{date:s.date,time:s.time},durMin:e&&!s.dateOnly?Math.max(0,ical.minutesOf(e.date,e.time)-ical.minutesOf(s.date,s.time)):0,spanDays:e&&s.dateOnly?Math.max(1,ical.toNum(e.date)-ical.toNum(s.date)+1):1,rule:null,exdates:[],rdates:[]});}return out;}
function extract(html,url){const ns=nodes(html),facts=[],add=(key,value,method)=>{value=clip(value);if(value&&!facts.some(f=>f.key===key&&f.value===value))facts.push({id:hash(key+value+url),key,value,sourceURL:url,method});};for(const n of ns){if([].concat(n['@type']||[]).some(t=>/Event$/.test(t)))continue;const isPlace=[].concat(n['@type']||[]).some(t=>/Business|Store|Restaurant|Library|Organization|Place|Church|FoodEstablishment|Cafe|BarOrPub|Museum|Service|Venue/.test(t));if(!isPlace&&!n.telephone&&!n.address&&!n.openingHours&&!n.openingHoursSpecification)continue;for(const v of [].concat(n.sameAs||[])){const social=Social.parse(v,url);if(social)add('social',social.url,'Structured website connection');}add('name',n.name,'Structured website data');add('phone',n.telephone,'Structured website data');const a=n.address;if(a)add('address',typeof a==='string'?a:[a.streetAddress,a.addressLocality,a.addressRegion,a.postalCode].filter(Boolean).join(', '),'Structured website data');if(n.openingHours)add('hours',[].concat(n.openingHours).join('; '),'Structured website data');for(const h of [].concat(n.openingHoursSpecification||[])){if(!h||typeof h!=='object')continue;add('hours',[].concat(h.dayOfWeek||[]).map(d=>String(d).split('/').pop()).join(', ')+': '+(h.opens||'?')+'–'+(h.closes||'?'),'Structured website data');}}
for(const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){const a=attributes(m[1]);if(/^tel:/i.test(a.href||''))add('phone',a.href.slice(4),'Published phone link');}
const readable=String(html).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<\/(?:p|div|li|tr|section|h[1-6])\s*>|<br\s*\/?\s*>/gi,'\n').split('\n').map(plain);for(const line of readable)if(line.length<300&&/\b(?:hours|mon(?:day)?|tue(?:sday)?|wed(?:nesday)?|thu(?:rsday)?|fri(?:day)?|sat(?:urday)?|sun(?:day)?)\b/i.test(line)&&/\d\s*(?::\d\d)?\s*(?:am|pm)|\d\d:\d\d|closed/i.test(line))add('hours',line,'Suggested text excerpt · Check context');const ls=links(html,url);for(const l of ls){const social=Social.parse(l.url);if(social)add('social',social.url,'Published social link');}return {facts:facts.slice(0,25),events:structuredEvents(ns,url),links:ls,calendars:ls.filter(l=>l.calendar||/text\/calendar/i.test(l.type)||/\.ics(?:[?#]|$)|icalendar|[?&]ical=|\/ical\/|export\.ics|calendar\/export/i.test(l.url)).slice(0,8)};}
function flatten(parsed,url){const today=ical.wallOf(Date.now(),TZ).date,to=ical.fromNum(ical.toNum(today)+180);return ical.expandAll(parsed,today,to).slice(0,200).filter(e=>e.title&&e.date).map(e=>({uid:hash((e.uid||e.title)+'|'+e.date+'|'+e.time),title:clip(e.title,140),date:e.date,time:e.time||'',end:e.endTime||'',endDate:e.endDate||'',note:plain(e.detail),location:clip(e.location,250),sourceURL:url}));}
async function inspect(input,{reader=fetchPublic}={}){const initial=normalize(input),started=Date.now(),robots=new Map(),warnings=[],read=async url=>{if(Date.now()-started>25000)throw new Error('Website scan reached its time limit.');const u=new URL(url);if(!robots.has(u.origin)){try{const r=await reader(u.origin+'/robots.txt');robots.set(u.origin,r.body);}catch(e){if(e.httpStatus===404||e.httpStatus===410)robots.set(u.origin,'');else throw new Error('Could not check this website’s automated-reader rules. Try its direct calendar address later.');}}if(!robotsAllows(robots.get(u.origin),u.pathname+u.search))throw new Error('This website asks automated readers not to read that page.');const result=await reader(url);if(result.url!==url){const final=new URL(result.url);if(!robots.has(final.origin)){try{robots.set(final.origin,(await reader(final.origin+'/robots.txt')).body);}catch(e){if(e.httpStatus===404||e.httpStatus===410)robots.set(final.origin,'');else throw e;}}if(!robotsAllows(robots.get(final.origin),final.pathname+final.search))throw new Error('The destination asks automated readers not to read this page.');}return result;};
const first=await read(initial),retrievedAt=new Date().toISOString();if(/BEGIN:VCALENDAR/i.test(first.body.slice(0,5000))){const events=flatten(ical.parseIcs(first.body,TZ),first.url);return {url:first.url,retrievedAt,facts:[],events,calendars:[],readPages:[first.url],warnings:events.length?[]:['No upcoming readable entries in the next 180 days.'],isFeed:true};}if(!/html/i.test(first.type)&&!/<html|<script|<body/i.test(first.body))throw new Error('This address does not publish a readable webpage or iCalendar feed.');const found=extract(first.body,first.url),readPages=[first.url],facts=found.facts,events=flatten(found.events,first.url),calendars=found.calendars.map(c=>({...c,sourceURL:first.url}));const more=[...new Set(found.links.filter(l=>new URL(l.url).origin===new URL(first.url).origin&&/contact|opening.?hours|\/hours|\/events|\/calendar/i.test(l.url+' '+l.label)&&!calendars.some(c=>c.url===l.url)).map(l=>l.url))].filter(u=>u!==first.url).slice(0,3);for(const url of more){try{const page=await read(url),x=extract(page.body,page.url);readPages.push(page.url);facts.push(...x.facts);events.push(...flatten(x.events,page.url));calendars.push(...x.calendars.map(c=>({...c,sourceURL:page.url})));}catch(e){warnings.push(new URL(url).pathname+': '+e.message);}}
return {url:first.url,retrievedAt,facts:[...new Map(facts.map(f=>[f.key+'|'+f.value,f])).values()].slice(0,40),events:[...new Map(events.map(e=>[e.title+'|'+e.date+'|'+e.time,e])).values()].slice(0,200),calendars:[...new Map(calendars.map(c=>[c.url,c])).values()].slice(0,8),readPages,warnings,isFeed:false};}
let busy=false;const cache=new Map();async function cachedInspect(url){url=normalize(url);const cached=cache.get(url);if(cached&&Date.now()-cached.time<15*60000)return cached.result;if(busy)throw Object.assign(new Error('Another website is being read. Try again in a moment.'),{status:429});busy=true;try{const result=await inspect(url);if(cache.size>=50)cache.delete(cache.keys().next().value);cache.set(url,{time:Date.now(),result});return result;}finally{busy=false;}}
module.exports={inspect:cachedInspect,inspectWith:inspect,extract,normalize,publicIP,robotsAllows,flatten};
